# Generated by Django 4.2.15 on 2024-09-11 06:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('activity', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysioSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('appointment_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysioUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('id_number', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('education', models.TextField(null=True)),
                ('years_of_experience', models.IntegerField(null=True)),
                ('specialty', models.TextField(null=True)),
                ('pck_number', models.IntegerField(null=True)),
                ('description', models.TextField(default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='assets/patient_images/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PostVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField()),
                ('treatment_plan', models.TextField()),
                ('recommendations', models.TextField()),
                ('follow_up_date', models.DateField()),
                ('pain_management', models.TextField()),
                ('feedback', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser')),
            ],
        ),
    ]
