# Generated by Django 5.0.4 on 2024-06-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('activity', models.CharField(max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser')),
            ],
        ),
    ]
