# Generated by Django 4.2.15 on 2024-09-11 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physiotherapist', '0001_initial'),
        ('app_physio', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiouser',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='physiotherapist.physiotherapistcategories'),
        ),
        migrations.AddField(
            model_name='physiouser',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='manager.manager'),
        ),
        migrations.AddField(
            model_name='physioschedule',
            name='physio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser'),
        ),
        migrations.AddField(
            model_name='physiolog',
            name='physio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser'),
        ),
    ]
