# Generated by Django 5.0.4 on 2024-06-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0002_physiolog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physiolog',
            old_name='patient',
            new_name='physio',
        ),
    ]
