# Generated by Django 5.0.4 on 2024-06-07 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0003_rename_patient_physiolog_physio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysioSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('appointment_type', models.CharField(max_length=50, null=True)),
                ('physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser')),
            ],
        ),
    ]
