# Generated by Django 4.2.15 on 2024-08-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0006_physiouser_pck_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiouser',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
