# Generated by Django 5.0.4 on 2025-01-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0007_physiolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiouser',
            name='clinic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
