# Generated by Django 4.2.15 on 2024-08-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0005_alter_physiotherapistcategories_description'),
        ('app_physio', '0007_physiouser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiouser',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='physiotherapist.physiotherapistcategories'),
        ),
    ]
