# Generated by Django 4.2.15 on 2024-08-18 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('app_physio', '0008_physiouser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiouser',
            name='created_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='manager.manager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physiouser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physiouser',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
