# Generated by Django 5.0.4 on 2025-02-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0008_physiouser_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiouser',
            name='home_address',
            field=models.TextField(null=True),
        ),
    ]
