# Generated by Django 5.0.4 on 2025-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0009_physiouser_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiouser',
            name='years_of_experience',
            field=models.TextField(null=True),
        ),
    ]
