# Generated by Django 4.2.15 on 2024-09-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0009_physiouser_created_by_physiouser_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiouser',
            name='image',
            field=models.ImageField(null=True, upload_to='assets/patient_images/'),
        ),
    ]
