# Generated by Django 5.0.4 on 2025-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0010_alter_physiouser_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvisit',
            name='follow_up_date',
            field=models.DateField(null=True),
        ),
    ]
