# Generated by Django 4.2.15 on 2024-09-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsDlr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20)),
                ('correlator', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('product_id', models.CharField(max_length=100)),
                ('campaign_id', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
                ('billing_type', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_status', models.CharField(max_length=100)),
            ],
        ),
    ]
