# Generated by Django 4.2.15 on 2024-08-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0009_physiouser_created_by_physiouser_created_date_and_more'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysioClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser')),
            ],
        ),
    ]
