# Generated by Django 4.2.15 on 2024-09-03 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0009_physiouser_created_by_physiouser_created_date_and_more'),
        ('clinics', '0003_clinicimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('visit_date', models.DateTimeField()),
                ('visit_reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('images', models.ManyToManyField(blank=True, null=True, to='clinics.clinicimages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser')),
            ],
        ),
    ]
