# Generated by Django 4.2.15 on 2024-09-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinicreviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicreviews',
            name='images',
        ),
    ]
