# Generated by Django 4.2.15 on 2024-09-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_rename_timestamp_appointment_start_time'),
        ('clinics', '0005_remove_clinicreviews_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicreviews',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.appointment'),
        ),
    ]
