# Generated by Django 4.2.15 on 2024-09-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_clinicreviews_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='open_time',
            field=models.TimeField(null=True),
        ),
    ]
