# Generated by Django 4.2.15 on 2024-09-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinic_close_time_clinic_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='close_time',
            field=models.TimeField(default='8:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='open_time',
            field=models.TimeField(),
        ),
    ]
