# Generated by Django 4.2.15 on 2024-09-03 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_rename_timestamp_appointment_start_time'),
        ('clinics', '0008_alter_clinic_close_time_alter_clinic_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicreviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
