# Generated by Django 4.2.15 on 2024-09-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
