# Generated by Django 4.2.15 on 2024-09-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0026_alter_patient_phone_number'),
        ('mpesa', '0002_delete_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaDepositErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_id', models.CharField(max_length=256)),
                ('error_code', models.CharField(max_length=256)),
                ('error_msg', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
