# Generated by Django 4.2.15 on 2024-09-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_alter_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesacallbackresponse',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
