# Generated by Django 4.2.15 on 2024-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_mpesadepositerrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='customer_message',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='response_code',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='response_description',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
