# Generated by Django 4.2.15 on 2024-09-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0004_mpesapayment_customer_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='status',
            field=models.IntegerField(default=0, max_length=256),
        ),
    ]
