# Generated by Django 4.2.15 on 2024-09-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0005_mpesapayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
