# Generated by Django 4.2.15 on 2024-09-09 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0006_alter_mpesapayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='checkout_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='merchant_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='MpesaCallBackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_code', models.CharField(max_length=256)),
                ('result_description', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpesa.mpesapayment')),
            ],
        ),
    ]
