# Generated by Django 4.2.15 on 2024-09-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0007_alter_mpesapayment_checkout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacallbackresponse',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
