# Generated by Django 4.2.15 on 2024-09-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0008_mpesacallbackresponse_mpesa_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacallbackresponse',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesacallbackresponse',
            name='transaction_date',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
