# Generated by Django 5.0.4 on 2024-04-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
