# Generated by Django 5.0.4 on 2024-04-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_alter_adminuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='id_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='years_of_experience',
            field=models.DateTimeField(null=True),
        ),
    ]
