# Generated by Django 5.0.4 on 2024-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_adminuser_date_of_birth_adminuser_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
