# Generated by Django 5.0.4 on 2024-05-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_serviceprovided'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('resource_type', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
