# Generated by Django 4.2.15 on 2024-09-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_problem',
            field=models.CharField(default='None', max_length=500),
            preserve_default=False,
        ),
    ]
