# Generated by Django 5.0.4 on 2024-04-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patientlog_id_patientfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
