# Generated by Django 5.0.4 on 2024-05-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_appointment_id_appointmentcancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(max_length=50, null=True)),
                ('fine_percentage', models.IntegerField(null=True)),
                ('duration', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointmentcancellation',
            name='penalty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.penalty'),
        ),
    ]
