# Generated by Django 5.0.4 on 2024-05-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_penalty_appointmentcancellation_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='chronic_disease_history',
        ),
    ]
