# Generated by Django 5.0.4 on 2024-05-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_chronicdisease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChronicDisease',
        ),
    ]
