# Generated by Django 5.0.4 on 2024-05-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_delete_chronicdisease'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chronic_disease_history',
            field=models.TextField(null=True),
        ),
    ]
