# Generated by Django 5.0.4 on 2024-06-07 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0004_physioschedule'),
        ('patient', '0013_appointment_created_date_appointment_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='physiotherapist',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser'),
        ),
    ]
