# Generated by Django 5.0.4 on 2024-06-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0004_physioschedule'),
        ('patient', '0014_appointment_physiotherapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfeedback',
            name='physiotherapist',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser'),
        ),
    ]
