# Generated by Django 5.0.4 on 2025-01-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_patientlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('request_id', models.CharField(max_length=50, null=True)),
                ('checkout_id', models.CharField(max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
