# Generated by Django 4.2.15 on 2024-08-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0009_physiouser_created_by_physiouser_created_date_and_more'),
        ('patient', '0018_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='physiotherapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser'),
        ),
    ]
