# Generated by Django 5.0.4 on 2025-01-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_mpesapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='status_message',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
