# Generated by Django 5.0.4 on 2025-01-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_mpesapayment_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='home_address',
            field=models.TextField(null=True),
        ),
    ]
