# Generated by Django 4.2.15 on 2024-08-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_alter_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='timestamp',
            new_name='start_time',
        ),
    ]
