# Generated by Django 5.0.4 on 2025-03-04 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physio', '0010_alter_physiouser_years_of_experience'),
        ('patient', '0021_patient_home_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.TextField()),
                ('category', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('physio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_physio.physiouser')),
            ],
        ),
    ]
