# Generated by Django 4.2.15 on 2024-09-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_rename_timestamp_appointment_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
