# Generated by Django 5.0.4 on 2025-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_videorecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecommendation',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videorecommendation',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videorecommendation',
            name='patient_comments',
            field=models.TextField(null=True),
        ),
    ]
