# Generated by Django 4.2.15 on 2024-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_payment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
