# Generated by Django 5.0.4 on 2025-03-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_videorecommendation_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecommendation',
            name='patient_comments',
            field=models.TextField(default='', null=True),
        ),
    ]
