# Generated by Django 5.0.4 on 2025-03-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_alter_videorecommendation_patient_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.appointment'),
            preserve_default=False,
        ),
    ]
