# Generated by Django 4.2.15 on 2024-09-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_alter_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='0726635455', max_length=15),
            preserve_default=False,
        ),
    ]
