# Generated by Django 5.0.4 on 2024-04-21 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
        ("physiotherapist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Physiotherapy",
            new_name="Physiotherapist",
        ),
    ]
