# Generated by Django 4.2.15 on 2024-09-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapistcategories',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='physiotherapistcategories',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='assets/physiotherapist_categories/'),
            preserve_default=False,
        ),
    ]
