# Generated by Django 4.2.15 on 2024-08-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0002_rename_physiotherapy_physiotherapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysiotherapistCategories',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/physiotherapist_categories/')),
            ],
        ),
        migrations.AddField(
            model_name='physiotherapist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='physiotherapist.physiotherapistcategories'),
        ),
    ]
