# Generated by Django 4.2.15 on 2024-09-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0002_alter_physiotherapistcategories_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapistcategories',
            name='image',
            field=models.ImageField(upload_to='assets/physiotherapist_categories/'),
        ),
    ]
