# Generated by Django 4.2.15 on 2024-08-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0003_physiotherapistcategories_physiotherapist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapistcategories',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
