# Generated by Django 4.2.15 on 2024-08-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0004_physiotherapistcategories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapistcategories',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
