# Generated by Django 4.2.15 on 2024-09-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(default='', upload_to='assets/managers/'),
            preserve_default=False,
        ),
    ]
